
'use strict';

var path = require('path');
var webpack = require("webpack");
// var node_modules_dir = path.resolve(__dirname, 'node_modules');

module.exports = {
  entry: {
    client: "./app/js/app",
    vendor: ["jquery", "underscore", "react", "firebase", "reactfire" ]
  },
  output: {
    path: __dirname + "/build/js",
    publicPath: "/js/",
    filename: "[name].js"
  },
  module: {
    loaders: [
      { test: /\.js?$/, loaders: ['react-hot', 'babel'], exclude: /node_modules/ },
      { test: /\.js$/, exclude: /node_modules/, loader: 'babel-loader'}
    ]
  },
  resolve: {
    extensions: ["", ".js", ".scss", ".html"]
  }
  ,
  plugins: [
    new webpack.optimize.CommonsChunkPlugin("vendor", "vendor.scripts.js")
  ]
};

// ---
// generated by coffee-script 1.9.2
