
'use strict';

var path = require('path');
var webpack = require("webpack");
var HtmlWebpackPlugin = require('html-webpack-plugin');
// var node_modules_dir = path.resolve(__dirname, 'node_modules');

module.exports = {
  entry: {
    client: "./app/js/app",
    vendor: ["jquery", "backbone", "underscore", "react", "firebase"]
  },
  output: {
    path: __dirname + "/build/js",
    publicPath: "/js/",
    filename: "[name].js"
  },
  module: {
    loaders: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel'
      }
    ]
  },
  resolve: {
    extensions: ["", ".js", ".scss", ".html"]
  }
  ,
  plugins: [
    new webpack.optimize.CommonsChunkPlugin("vendor", "vendor.scripts.js")
  ]
};

// ---
// generated by coffee-script 1.9.2
